<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPuwh3tv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPuwh3tv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPuwh3tv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPuwh3tv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPuwh3tv\appProdProjectContainer([
    'container.build_hash' => 'Puwh3tv',
    'container.build_id' => '966e740d',
    'container.build_time' => 1610544189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPuwh3tv');
